python -u run.py \
  --is_training 1 \
  --root_path ./all_datasets/SMD \
  --model_name SMD \
  --model GPT4TS \
  --data SMD \
  --seq_len 100 \
  --d_model 768 \
  --d_ff 768 \
  --gpt_layer 6 \
  --enc_in 38 \
  --c_out 38 \
  --anomaly_ratio 0.5 \
  --batch_size 128 \
  --patch_size 25 \
  --stride 1 \
  --train_epochs 5 \
  --visualize 0 \
  --use_feature_embedding 1 \
  --use_prompt_pool 1 \
  --use_skip_embedding 1 \
  --nb_random_samples 10 \
  --top_k 5 \
  --pool_size 10 \
  --prompt_len 5