python -u run.py \
  --is_training 1 \
  --root_path ./all_datasets/SWaT \
  --model_id SWAT \
  --model GPT4TS \
  --data SWAT \
  --seq_len 100 \
  --gpt_layer 6 \
  --d_model 768 \
  --d_ff 128 \
  --patch_size 1 \
  --stride 1 \
  --enc_in 51 \
  --c_out 51 \
  --anomaly_ratio 1 \
  --batch_size 128 \
  --learning_rate 0.0001 \
  --train_epochs 10 \
  --use_skip_embedding 1 \
  --use_prompt_pool 1 \
  --use_feature_embedding 1 \
  --nb_random_samples 1 \
  --feature_epochs 10 \
  --channels 25 \
  --prompt_len 5 \
  --top_k 5 \
  --pool_size 10
